import { createDownloadLink } from "@/lib/s3";
import { getFileId } from "@/lib/file-key";

export const runtime = "nodejs";
const headers = { "Cache-Control": "no-store" };

export async function POST(request: Request) {
  const origin = request.headers.get("origin");
  if (origin && origin !== new URL(request.url).origin) {
    return Response.json({ error: "Link requests must come from this site." }, { status: 403, headers });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: "Send valid JSON with the uploaded file key." }, { status: 400, headers });
  }

  // Only accept the exact key format generated by Cloudrop's upload endpoint.
  if (!body || typeof body !== "object" || !("key" in body) || typeof body.key !== "string" ||
    !getFileId(body.key)) {
    return Response.json({ error: "The uploaded file key is invalid." }, { status: 400, headers });
  }

  try {
    return Response.json(await createDownloadLink(body.key), { headers });
  } catch {
    // Do not expose raw AWS errors, credentials, or signed URLs in logs.
    return Response.json({ error: "Your upload finished, but a download link could not be created. Try again. If this continues, check the server’s S3 read permission and that the file still exists." }, { status: 503, headers });
  }
}
